// @ts-check

/**
 * Creating multiple sidebars enables you to:
 * - Separate documentation and release notes into distinct categories.
 * - Render different sidebars for different sections of the site.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Sidebar for Documentation
  docsSidebar: [
  {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials', // Automatically generates items from docs/tutorials
        },
      ],
    },
    {
      type: 'category',
      label: 'How-to Guides',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'how-to-guides', // Automatically generates items from docs/how-to-guides
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference', // Automatically generates items from docs/references
        },
      ],
    },
    {
      type: 'category',
      label: 'Explanation',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'explanation', // Automatically generates items from docs/references
        },
      ],
    },    
  ],

  // Sidebar for Release Notes
  releaseNotesSidebar: [
    {
      type: 'category',
      label: 'Release Notes',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'release-notes', // Automatically generates items from docs/release-notes
        },
      ],
    },
  ],
  videoGuidesSidebar: [
    {
      type: 'category',
      label: 'Video Guides',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'video-guides', 
        },
      ],
    },
  ],

};

export default sidebars;
